version: "3"
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=community
      - POSTGRES_USER=frustacean
      - POSTGRES_PASSWORD=abc123
    ports:
      - '5434:5432'

